### PR TITLE
GalaxiteUtils 0.4.0

### PR DESCRIPTION
**Pull request by 1unar-Eclipse**
For the latter: .execute is a long string to remember for running code. Could definitely be changed to be something else if "> " is too likely to be fired on accident (maybe ">> "? one > may be used for that one meme style based on 4chan, but a double is not nearly as common)

### CODE REVIEW

**Comment by Plextora** [comment]
I kind of have mixed opinions on this. Yeah using just `> ` for repl execution would be a fast shorthand but `.exec` has already been set as an alias for the command. Having another one just feels redundant to me (maybe @Imrglop could weigh in on this :trollface: ). Maybe you could make another PR for the GalaxiteUtils update and revert the GalaxiteUtils update in this PR in the meantime

**Comment by 1unar-Eclipse** [comment]
...in looking through the code I somehow failed to notice `.exec` existed, oops. I can undo that part, they were separate commits for a reason.

Sidenote, could there be a way to see command aliases in Latite?

**Comment by 1unar-Eclipse** [comment]
Repl change reverted! Also there are doomguy emojis for some reason :suspect: as well as my new favorite, :shipit:

**Comment by Plextora** [comment]
> ...in looking through the code I somehow failed to notice `.exec` existed, oops. I can undo that part, they were separate commits for a reason.
> 
> Sidenote, could there be a way to see command aliases in Latite?

It might be listed in the .help command but I'm not gonna test right now

**Pull request merged**
